name: CI/CD Pipeline
on: workflow_dispatch
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: cache maven dependencies
          uses: actions/cache@v3
          with:
            path: ~/.m2
            key: ${{ runner.os }}-maven-${{ hashFiles('./boardgame/my-app/pom.xml') }} 
        - name: setup jdk
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: install maven
          run: sudo apt-get install maven -y
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: build with maven
          run: mvn clean install
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Checkout code
          uses: actions/checkout@v3 
        - name: run tests
          run: mvn test
  package-and-upload:
    runs-on: ubuntu-latest
    needs: test
    steps:
        - name: package application
          run: mvn package
        - name: upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: my-app-artifact
            path: target/*.jar
  scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
        - name: trivy fs scan
          run: | 
            trivy fs . --format table -o trivy-logs.html
  sonarqube:
    runs-on: ubuntu-latest
    needs: test
    environment: main
    steps:
        - name: SonarQube Scan
          uses: sonarsource/sonarcloud-github-action@v2
          with:
            args: >
              -Dsonar.projectKey=github-actions
              -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}   
        - name: install jq
          run: sudo apt-get install jq -y
        - name: get quality gate status
          id: quality_gate
          run: |
            response=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: ${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=github-actions)
            echo "response=$response" >> $GITHUB_OUTPUT
            status=$(echo "$response" | jq -r '.projectStatus.status')
            echo "quality_gate_status=$status" >> $GITHUB_OUTPUT
        - name: check quality gate status
          if: ${{ steps.quality_gate.outputs.quality_gate_status != 'OK' }}
          run: exit 1
              
  qemu-setup:
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
        - name: setup qemu
          run: |
            sudo apt-get update
            sudo apt-get install -y qemu-user-static
        - name: setup qemu action    
          uses: docker/setup-qemu-action@v2
          with:
            image: qemu-user-static

  docker-build:
    runs-on: ubuntu-latest
    needs: qemu-setup
    steps:
        - name: setup docker buildx
          uses: docker/setup-buildx-action@v2
        - name: build docker image
          run: |
            docker build -t thejyot/my-app:latest .    
  
  docker-image-scan:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
        - name: scan docker image with trivy
          run: trivy image --format table -o trivy-image-scan.html thejyot/my-app:latest
  login-and-push:
    runs-on: ubuntu-latest
    needs: docker-image-scan
    environment: main
    steps:
        - name: login to docker hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: push docker image
          run: docker push thejyot/my-app:latest
  kubernetes:
    runs-on: ubuntu-latest
    needs: login-and-push
    environment: main
    steps:
        - name: setup kubeconfig
          uses: tale/kubeconfig-action@v1
          with:
            base64-kubeconfig: ${{ secrets.KUBECONFIG_BASE64 }}
        - name: deploy to kubernetes cluster
          run: |
            kubectl apply -f boardgame/deployment-service.yaml
    

